### ISSUE TITLE
Add CSP library

### ISSUE THREAD

**Issue by ryanjtr** [Caxaho/CSP-CAN-FreeRTOS#1]
Excuse me sir, i`m new in this lib. Can u tell me how to add that lib to Stm32 project and build static lib like what u did?

**Comment by Caxaho** [comment]
Honestly I don't remember much about this project since it was a long time ago. The code in the repo should be a perfect blank slate to start from with FreeRTOS + CSP implemented on an STM32 board. Specifically an STM32F746ZGT. 

Off the top of my head though, to build a static library for CSP you need to use the WAF build system or meson (though I never had any luck with meson). This is all documented within the official CSP repo (https://github.com/libcsp/libcsp). I remember having to fiddle with the 'wscript' file. I also remember having to ensure that both the build script and the STM32 code used hard floats (or at least just the same type of float).

Unfortunately I cannot help you further than that as I simply do not remember. I hope that helps!
